"""initial_schema

Revision ID: 222ceea7a25a
Revises: 
Create Date: 2026-06-07 00:26:44.997488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '222ceea7a25a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('morning_queue',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('header_he', sa.Text(), nullable=False),
    sa.Column('oars_affirmation_he', sa.Text(), nullable=False),
    sa.Column('habit_reset_he', sa.Text(), nullable=False),
    sa.Column('queued_at_utc', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_morning_queue_user_id'), 'morning_queue', ['user_id'], unique=False)
    op.create_table('notifications_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('notification_type', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('sent_at', sa.String(length=64), nullable=False),
    sa.Column('iso_week', sa.String(length=16), nullable=False),
    sa.Column('current_week', sa.Integer(), nullable=False),
    sa.Column('push_message', sa.Text(), nullable=False),
    sa.Column('oars_question', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_log_user_id'), 'notifications_log', ['user_id'], unique=False)
    op.create_table('sos_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('week_context', sa.Integer(), nullable=False),
    sa.Column('timestamp_utc', sa.String(length=64), nullable=False),
    sa.Column('resolution_status', sa.String(length=16), nullable=True),
    sa.Column('resolved_at_utc', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sos_events_user_id'), 'sos_events', ['user_id'], unique=False)
    op.create_table('user_states',
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('current_week', sa.Integer(), nullable=False),
    sa.Column('is_prepped', sa.Boolean(), nullable=False),
    sa.Column('baseline_rhr', sa.Integer(), nullable=True),
    sa.Column('last_notified_iso_week', sa.String(length=16), nullable=True),
    sa.Column('last_notified_week', sa.Integer(), nullable=True),
    sa.Column('last_notified_timestamp', sa.String(length=64), nullable=True),
    sa.Column('notifications_sent', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_states')
    op.drop_index(op.f('ix_sos_events_user_id'), table_name='sos_events')
    op.drop_table('sos_events')
    op.drop_index(op.f('ix_notifications_log_user_id'), table_name='notifications_log')
    op.drop_table('notifications_log')
    op.drop_index(op.f('ix_morning_queue_user_id'), table_name='morning_queue')
    op.drop_table('morning_queue')
    # ### end Alembic commands ###
